//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CoffeeManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _lock {
            get {
                object obj = ResourceManager.GetObject("lock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap accept {
            get {
                object obj = ResourceManager.GetObject("accept", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap accept24 {
            get {
                object obj = ResourceManager.GetObject("accept24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap add {
            get {
                object obj = ResourceManager.GetObject("add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap add16 {
            get {
                object obj = ResourceManager.GetObject("add16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bill16 {
            get {
                object obj = ResourceManager.GetObject("bill16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap billPlease {
            get {
                object obj = ResourceManager.GetObject("billPlease", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cancel {
            get {
                object obj = ResourceManager.GetObject("cancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cancel24 {
            get {
                object obj = ResourceManager.GetObject("cancel24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap category {
            get {
                object obj = ResourceManager.GetObject("category", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap changeTable {
            get {
                object obj = ResourceManager.GetObject("changeTable", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap close {
            get {
                object obj = ResourceManager.GetObject("close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap connect_icon {
            get {
                object obj = ResourceManager.GetObject("connect-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cus16 {
            get {
                object obj = ResourceManager.GetObject("cus16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Database_Backup_icon {
            get {
                object obj = ResourceManager.GetObject("Database-Backup-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap del16 {
            get {
                object obj = ResourceManager.GetObject("del16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dev16 {
            get {
                object obj = ResourceManager.GetObject("dev16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap edit16 {
            get {
                object obj = ResourceManager.GetObject("edit16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EngFlag {
            get {
                object obj = ResourceManager.GetObject("EngFlag", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập tên database.
        /// </summary>
        internal static string ERR_EMPTY_DBNNAME {
            get {
                return ResourceManager.GetString("ERR_EMPTY_DBNNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi truy cập dữ liệu.
        /// </summary>
        internal static string ERROR_ACCESS_DATA {
            get {
                return ResourceManager.GetString("ERROR_ACCESS_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi khi thêm hóa đơn.
        /// </summary>
        internal static string ERROR_ADD_BILL {
            get {
                return ResourceManager.GetString("ERROR_ADD_BILL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi khi thêm chi tiết hóa đơn.
        /// </summary>
        internal static string ERROR_ADD_BILLDT {
            get {
                return ResourceManager.GetString("ERROR_ADD_BILLDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi khi thêm dữ liệu.
        /// </summary>
        internal static string ERROR_ADDING_DATA {
            get {
                return ResourceManager.GetString("ERROR_ADDING_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu xác nhận không khớp.
        /// </summary>
        internal static string ERROR_CF_PASSWORD_NOT_MATCH {
            get {
                return ResourceManager.GetString("ERROR_CF_PASSWORD_NOT_MATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã tạo tài khoản đăng nhập cho người dùng này.
        /// </summary>
        internal static string ERROR_CREATED_ACCOUNT {
            get {
                return ResourceManager.GetString("ERROR_CREATED_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể xóa tài khoản admin.
        /// </summary>
        internal static string ERROR_DEL_ADMIN {
            get {
                return ResourceManager.GetString("ERROR_DEL_ADMIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi khi xóa người dùng.
        /// </summary>
        internal static string ERROR_DELETING_USER {
            get {
                return ResourceManager.GetString("ERROR_DELETING_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi khi sửa dữ liệu.
        /// </summary>
        internal static string ERROR_EDITING_DATA {
            get {
                return ResourceManager.GetString("ERROR_EDITING_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập tên server.
        /// </summary>
        internal static string ERROR_EMPTY_SERVERNAME {
            get {
                return ResourceManager.GetString("ERROR_EMPTY_SERVERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng xác nhận mật khẩu.
        /// </summary>
        internal static string ERROR_ENTER_CF_PASSWORD {
            get {
                return ResourceManager.GetString("ERROR_ENTER_CF_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập tên người dùng và mật khẩu.
        /// </summary>
        internal static string ERROR_ENTER_LOGIN {
            get {
                return ResourceManager.GetString("ERROR_ENTER_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập mật khẩu mới.
        /// </summary>
        internal static string ERROR_ENTER_NEW_PASSWORD {
            get {
                return ResourceManager.GetString("ERROR_ENTER_NEW_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cần phải điền ít nhất 1 thông tin của khách hàng.
        /// </summary>
        internal static string ERROR_ENTER_ONE_INFO {
            get {
                return ResourceManager.GetString("ERROR_ENTER_ONE_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập mật khẩu.
        /// </summary>
        internal static string ERROR_ENTER_PASSWORD {
            get {
                return ResourceManager.GetString("ERROR_ENTER_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập đơn vị tính.
        /// </summary>
        internal static string ERROR_ENTER_UNIT {
            get {
                return ResourceManager.GetString("ERROR_ENTER_UNIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập đơn giá.
        /// </summary>
        internal static string ERROR_ENTER_UNIT_PRICE {
            get {
                return ResourceManager.GetString("ERROR_ENTER_UNIT_PRICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập tên người dùng.
        /// </summary>
        internal static string ERROR_ENTER_USER {
            get {
                return ResourceManager.GetString("ERROR_ENTER_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi truy xuất dữ liệu.
        /// </summary>
        internal static string ERROR_ENTRIEVING_DATA {
            get {
                return ResourceManager.GetString("ERROR_ENTRIEVING_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đã tồn tại, vui lòng chọn tên khác.
        /// </summary>
        internal static string ERROR_EXISTS_NAME {
            get {
                return ResourceManager.GetString("ERROR_EXISTS_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi khi xuất file.
        /// </summary>
        internal static string ERROR_EXPORTING_PDF {
            get {
                return ResourceManager.GetString("ERROR_EXPORTING_PDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi lấy thông tin cửa hàng.
        /// </summary>
        internal static string ERROR_GETTING_STORE_INFO {
            get {
                return ResourceManager.GetString("ERROR_GETTING_STORE_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi load dữ liệu hóa đơn.
        /// </summary>
        internal static string ERROR_LOAD_DATA_BILL {
            get {
                return ResourceManager.GetString("ERROR_LOAD_DATA_BILL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load truy xuất database name.
        /// </summary>
        internal static string ERROR_LOAD_DB {
            get {
                return ResourceManager.GetString("ERROR_LOAD_DB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi khi load nhóm.
        /// </summary>
        internal static string ERROR_LOAD_GROUP {
            get {
                return ResourceManager.GetString("ERROR_LOAD_GROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi khi load khu vực.
        /// </summary>
        internal static string ERROR_LOADING_AREA {
            get {
                return ResourceManager.GetString("ERROR_LOADING_AREA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi thao tác dữ liệu người dùng.
        /// </summary>
        internal static string ERROR_MANIPULATING_USER {
            get {
                return ResourceManager.GetString("ERROR_MANIPULATING_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian kết thúc không được nhỏ hơn thời gian bắt đầu.
        /// </summary>
        internal static string ERROR_NOT_LESS_TIME {
            get {
                return ResourceManager.GetString("ERROR_NOT_LESS_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình ảnh không được lớn hơn kích thước 64x64, Kích thước hiện tại là: .
        /// </summary>
        internal static string ERROR_OUT_SIZE_IMAGE {
            get {
                return ResourceManager.GetString("ERROR_OUT_SIZE_IMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập tên.
        /// </summary>
        internal static string ERROR_PRODUCT_NAME_EMPTY {
            get {
                return ResourceManager.GetString("ERROR_PRODUCT_NAME_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập giá sản phẩm.
        /// </summary>
        internal static string ERROR_PRODUCT_PRICE_EMPTY {
            get {
                return ResourceManager.GetString("ERROR_PRODUCT_PRICE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập số lượng sản phẩm.
        /// </summary>
        internal static string ERROR_PRODUCT_QUANTITY_EMPTY {
            get {
                return ResourceManager.GetString("ERROR_PRODUCT_QUANTITY_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi truy xuất thông tin Đăng nhập theo ID người dùng.
        /// </summary>
        internal static string ERROR_RETRIEVING_LOGIN_INFO {
            get {
                return ResourceManager.GetString("ERROR_RETRIEVING_LOGIN_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi khi truy xuất tên người dùng.
        /// </summary>
        internal static string ERROR_RETRIEVING_USER {
            get {
                return ResourceManager.GetString("ERROR_RETRIEVING_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi khi lưu dữ liệu.
        /// </summary>
        internal static string ERROR_SAVE_DATA {
            get {
                return ResourceManager.GetString("ERROR_SAVE_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn 1 tài khoản.
        /// </summary>
        internal static string ERROR_SELECT_AC {
            get {
                return ResourceManager.GetString("ERROR_SELECT_AC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vui lòng chọn nhân viên.
        /// </summary>
        internal static string ERROR_SELECT_EM {
            get {
                return ResourceManager.GetString("ERROR_SELECT_EM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã xảy ra lỗi.
        /// </summary>
        internal static string ERROR_SHOW_ERROR {
            get {
                return ResourceManager.GetString("ERROR_SHOW_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi khi chuyển bàn.
        /// </summary>
        internal static string ERROR_SWITCHING_TB {
            get {
                return ResourceManager.GetString("ERROR_SWITCHING_TB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi cập nhật trạng thái khi chuyển bàn.
        /// </summary>
        internal static string ERROR_UD_STATUS_TB {
            get {
                return ResourceManager.GetString("ERROR_UD_STATUS_TB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi cập nhật hóa đơn.
        /// </summary>
        internal static string ERROR_UPDATE_BILL {
            get {
                return ResourceManager.GetString("ERROR_UPDATE_BILL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi khi cập nhật trạng thái bill.
        /// </summary>
        internal static string ERROR_UPDATE_BILL_STATUS {
            get {
                return ResourceManager.GetString("ERROR_UPDATE_BILL_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi khi cập nhật trạng thái khách hàng.
        /// </summary>
        internal static string ERROR_UPDATE_CUS_STATUS {
            get {
                return ResourceManager.GetString("ERROR_UPDATE_CUS_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi khi cập nhật trạng thái bàn.
        /// </summary>
        internal static string ERROR_UPDATE_TABLE_STATUS {
            get {
                return ResourceManager.GetString("ERROR_UPDATE_TABLE_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi khi cập nhật trạng thái bàn.
        /// </summary>
        internal static string ERROR_UPDATE_TB_STATUS {
            get {
                return ResourceManager.GetString("ERROR_UPDATE_TB_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy nhân viên có tên đăng nhập này.
        /// </summary>
        internal static string ERROR_USER_NOTFOUND {
            get {
                return ResourceManager.GetString("ERROR_USER_NOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi khi xóa .
        /// </summary>
        internal static string ERROR_WHEN_DEL {
            get {
                return ResourceManager.GetString("ERROR_WHEN_DEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi khi cập nhật.
        /// </summary>
        internal static string ERROR_WHEN_UPDATING {
            get {
                return ResourceManager.GetString("ERROR_WHEN_UPDATING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sai tên đăng nhập hoặc mật khẩu.
        /// </summary>
        internal static string ERROR_WRONG_USERNAME {
            get {
                return ResourceManager.GetString("ERROR_WRONG_USERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap excel32 {
            get {
                object obj = ResourceManager.GetObject("excel32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap exec {
            get {
                object obj = ResourceManager.GetObject("exec", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap exit16 {
            get {
                object obj = ResourceManager.GetObject("exit16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Extension {
            get {
                object obj = ResourceManager.GetObject("Extension", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap help {
            get {
                object obj = ResourceManager.GetObject("help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kết nối thành công.
        /// </summary>
        internal static string INF_CONNECT_SUCCESS {
            get {
                return ResourceManager.GetString("INF_CONNECT_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang load server, xin vui lòng chờ....
        /// </summary>
        internal static string INF_WAIT_LOAD_SERVER {
            get {
                return ResourceManager.GetString("INF_WAIT_LOAD_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap info {
            get {
                object obj = ResourceManager.GetObject("info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap language {
            get {
                object obj = ResourceManager.GetObject("language", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap login16 {
            get {
                object obj = ResourceManager.GetObject("login16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logout16 {
            get {
                object obj = ResourceManager.GetObject("logout16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap menu16 {
            get {
                object obj = ResourceManager.GetObject("menu16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap merge {
            get {
                object obj = ResourceManager.GetObject("merge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bàn đang có khách.
        /// </summary>
        internal static string MSG_ALREADY_OCCUPIED {
            get {
                return ResourceManager.GetString("MSG_ALREADY_OCCUPIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server chưa được cài đặt, vui lòng cài đặt SQL server trước khi tiếp tục.
        /// </summary>
        internal static string MSG_CHECK_INSTALL_SQL {
            get {
                return ResourceManager.GetString("MSG_CHECK_INSTALL_SQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn khu vực.
        /// </summary>
        internal static string MSG_CHOOSE_AREA {
            get {
                return ResourceManager.GetString("MSG_CHOOSE_AREA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhấn Yes để đăng xuất tài khoản.
        /// </summary>
        internal static string MSG_CLICK_YES_LOG_OUT {
            get {
                return ResourceManager.GetString("MSG_CLICK_YES_LOG_OUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhấn Yes để đóng ứng dụng.
        /// </summary>
        internal static string MSG_CLOSE_FORM {
            get {
                return ResourceManager.GetString("MSG_CLOSE_FORM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa thiết lập kết nối database, vui lòng thiết lập trước.
        /// </summary>
        internal static string MSG_CONNECT_STR_NONE {
            get {
                return ResourceManager.GetString("MSG_CONNECT_STR_NONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cơ sở dữ liệu không được tìm thấy, bạn có thể sử dụng chức năng Khôi phục cơ sở dữ liệu ở góc trên bên phải của biểu mẫu.
        /// </summary>
        internal static string MSG_DATABASE_NOT_FOUND {
            get {
                return ResourceManager.GetString("MSG_DATABASE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa tài khoản đăng nhập?.
        /// </summary>
        internal static string MSG_DEL_AC {
            get {
                return ResourceManager.GetString("MSG_DEL_AC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  sẽ bị xóa, Tiếp tục?.
        /// </summary>
        internal static string MSG_DEL_QUES {
            get {
                return ResourceManager.GetString("MSG_DEL_QUES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người dùng đang có một tài khoản đăng nhập, vui lòng xóa tài khoản đăng nhập trước..
        /// </summary>
        internal static string MSG_DELETE_LOGIN_FIRST {
            get {
                return ResourceManager.GetString("MSG_DELETE_LOGIN_FIRST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã xóa .
        /// </summary>
        internal static string MSG_DELETED {
            get {
                return ResourceManager.GetString("MSG_DELETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done!.
        /// </summary>
        internal static string MSG_DONE {
            get {
                return ResourceManager.GetString("MSG_DONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn vị trí lưu file khác ổ đĩa cài đặt SQL.
        /// </summary>
        internal static string MSG_DONT_SAVE_C {
            get {
                return ResourceManager.GetString("MSG_DONT_SAVE_C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập tên bàn.
        /// </summary>
        internal static string MSG_ENTER_TABLE {
            get {
                return ResourceManager.GetString("MSG_ENTER_TABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập tên người dùng.
        /// </summary>
        internal static string MSG_ENTER_USERNAME {
            get {
                return ResourceManager.GetString("MSG_ENTER_USERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi khi thiết lập cài đặt.
        /// </summary>
        internal static string MSG_ERROR_SETTING_UP {
            get {
                return ResourceManager.GetString("MSG_ERROR_SETTING_UP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not selected a transfer table or a receiving table!.
        /// </summary>
        internal static string MSG_HAVENT_CHOSEN_TB {
            get {
                return ResourceManager.GetString("MSG_HAVENT_CHOSEN_TB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa chọn bàn.
        /// </summary>
        internal static string MSG_HAVENT_SELECT_TABLE {
            get {
                return ResourceManager.GetString("MSG_HAVENT_SELECT_TABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chiều rộng tối đa 150, chiều cao tối đa 160.
        /// </summary>
        internal static string MSG_MAX_NUMBER {
            get {
                return ResourceManager.GetString("MSG_MAX_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn không có quyền thực hiện thao tác này..
        /// </summary>
        internal static string MSG_NO_RIGHT {
            get {
                return ResourceManager.GetString("MSG_NO_RIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số không được phép bằng 0.
        /// </summary>
        internal static string MSG_NOT_ALLOWED {
            get {
                return ResourceManager.GetString("MSG_NOT_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có gì để lưu.
        /// </summary>
        internal static string MSG_NOTHING_TO_SAVE {
            get {
                return ResourceManager.GetString("MSG_NOTHING_TO_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo.
        /// </summary>
        internal static string MSG_NOTIFICATION {
            get {
                return ResourceManager.GetString("MSG_NOTIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  ra khỏi danh sách.
        /// </summary>
        internal static string MSG_OUT_OF_LIST {
            get {
                return ResourceManager.GetString("MSG_OUT_OF_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập số.
        /// </summary>
        internal static string MSG_PRESS_NUMBER {
            get {
                return ResourceManager.GetString("MSG_PRESS_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa nhập số tiền khách thanh toán, bạn muốn tiếp tục không?.
        /// </summary>
        internal static string MSG_QUES_ACCEPT {
            get {
                return ResourceManager.GetString("MSG_QUES_ACCEPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phần mềm cần khởi động lại, nhấn OK để tiếp tục..
        /// </summary>
        internal static string MSG_RESET_LANG {
            get {
                return ResourceManager.GetString("MSG_RESET_LANG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the account to delete.
        /// </summary>
        internal static string MSG_SELECT_AC {
            get {
                return ResourceManager.GetString("MSG_SELECT_AC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn nhóm thực đơn trước.
        /// </summary>
        internal static string MSG_SELECT_GR_FIRST {
            get {
                return ResourceManager.GetString("MSG_SELECT_GR_FIRST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn bàn hoặc khách hàng trước.
        /// </summary>
        internal static string MSG_SELECT_TABLE_FIRST {
            get {
                return ResourceManager.GetString("MSG_SELECT_TABLE_FIRST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bàn chưa có khách.
        /// </summary>
        internal static string MSG_TABLE_EMPTY {
            get {
                return ResourceManager.GetString("MSG_TABLE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có muốn lưu dữ liệu trước khi rời đi?.
        /// </summary>
        internal static string MSG_WANT_TO_SAVE {
            get {
                return ResourceManager.GetString("MSG_WANT_TO_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  sẽ bị xóa, tiếp tục?.
        /// </summary>
        internal static string MSG_WILL_DELETE {
            get {
                return ResourceManager.GetString("MSG_WILL_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu không đúng.
        /// </summary>
        internal static string MSG_WRONG_PASSWORD {
            get {
                return ResourceManager.GetString("MSG_WRONG_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap noneImage {
            get {
                object obj = ResourceManager.GetObject("noneImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap nonimg {
            get {
                object obj = ResourceManager.GetObject("nonimg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap open {
            get {
                object obj = ResourceManager.GetObject("open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap open24 {
            get {
                object obj = ResourceManager.GetObject("open24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pass16 {
            get {
                object obj = ResourceManager.GetObject("pass16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pdf32 {
            get {
                object obj = ResourceManager.GetObject("pdf32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap permission16 {
            get {
                object obj = ResourceManager.GetObject("permission16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap QRZalo {
            get {
                object obj = ResourceManager.GetObject("QRZalo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap report16 {
            get {
                object obj = ResourceManager.GetObject("report16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Restore_Window_icon {
            get {
                object obj = ResourceManager.GetObject("Restore-Window-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Restore16 {
            get {
                object obj = ResourceManager.GetObject("Restore16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap save {
            get {
                object obj = ResourceManager.GetObject("save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap search16 {
            get {
                object obj = ResourceManager.GetObject("search16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap setting {
            get {
                object obj = ResourceManager.GetObject("setting", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap setting24 {
            get {
                object obj = ResourceManager.GetObject("setting24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap setting32 {
            get {
                object obj = ResourceManager.GetObject("setting32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Settings_icon {
            get {
                object obj = ResourceManager.GetObject("Settings-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap shop {
            get {
                object obj = ResourceManager.GetObject("shop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ: .
        /// </summary>
        internal static string SHOW_ADDRESS {
            get {
                return ResourceManager.GetString("SHOW_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã tồn tại.
        /// </summary>
        internal static string SHOW_ALREADY_EXIST {
            get {
                return ResourceManager.GetString("SHOW_ALREADY_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã hóa đơn: .
        /// </summary>
        internal static string SHOW_BILL_CODE {
            get {
                return ResourceManager.GetString("SHOW_BILL_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hóa đơn từ .
        /// </summary>
        internal static string SHOW_BILL_FROM {
            get {
                return ResourceManager.GetString("SHOW_BILL_FROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bàn đang có khách không thể xóa.
        /// </summary>
        internal static string SHOW_CANT_DEL {
            get {
                return ResourceManager.GetString("SHOW_CANT_DEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Tiếp tục?.
        /// </summary>
        internal static string SHOW_CONTINUE {
            get {
                return ResourceManager.GetString("SHOW_CONTINUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách khách hàng.
        /// </summary>
        internal static string SHOW_CUS_LIST {
            get {
                return ResourceManager.GetString("SHOW_CUS_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khách hàng đang chờ....
        /// </summary>
        internal static string SHOW_CUS_WAITING {
            get {
                return ResourceManager.GetString("SHOW_CUS_WAITING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày: .
        /// </summary>
        internal static string SHOW_DAY {
            get {
                return ResourceManager.GetString("SHOW_DAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhân viên: .
        /// </summary>
        internal static string SHOW_EMPLOYEES {
            get {
                return ResourceManager.GetString("SHOW_EMPLOYEES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .xls.
        /// </summary>
        internal static string SHOW_EXTENTION_XLS {
            get {
                return ResourceManager.GetString("SHOW_EXTENTION_XLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ năm .
        /// </summary>
        internal static string SHOW_FROM_YEAR {
            get {
                return ResourceManager.GetString("SHOW_FROM_YEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang có khách.
        /// </summary>
        internal static string SHOW_HAVE_GUEST {
            get {
                return ResourceManager.GetString("SHOW_HAVE_GUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haven&apos;t chosen a table yet.
        /// </summary>
        internal static string SHOW_HAVENT_CHOSEN_TB {
            get {
                return ResourceManager.GetString("SHOW_HAVENT_CHOSEN_TB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không hoạt động.
        /// </summary>
        internal static string SHOW_INACTIVE {
            get {
                return ResourceManager.GetString("SHOW_INACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thành tiền.
        /// </summary>
        internal static string SHOW_INTO_MONEY {
            get {
                return ResourceManager.GetString("SHOW_INTO_MONEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang hoạt động.
        /// </summary>
        internal static string SHOW_IS_ACTIVE {
            get {
                return ResourceManager.GetString("SHOW_IS_ACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @key#yek.
        /// </summary>
        internal static string SHOW_KEY_ENCRYPT {
            get {
                return ResourceManager.GetString("SHOW_KEY_ENCRYPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang load dữ liệu, vui lòng chờ....
        /// </summary>
        internal static string SHOW_LOADING_DATA {
            get {
                return ResourceManager.GetString("SHOW_LOADING_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm đồ uống (thức ăn) vào hóa đơn.
        /// </summary>
        internal static string SHOW_NAME_ADD_BILLDT {
            get {
                return ResourceManager.GetString("SHOW_NAME_ADD_BILLDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa có khách.
        /// </summary>
        internal static string SHOW_NO_GUEST_YET {
            get {
                return ResourceManager.GetString("SHOW_NO_GUEST_YET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SHOW_NONE {
            get {
                return ResourceManager.GetString("SHOW_NONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng.
        /// </summary>
        internal static string SHOW_NUMBER {
            get {
                return ResourceManager.GetString("SHOW_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khách hàng cũ.
        /// </summary>
        internal static string SHOW_OLD_CUSTOMERS {
            get {
                return ResourceManager.GetString("SHOW_OLD_CUSTOMERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF file (*.pdf)|*.pdf.
        /// </summary>
        internal static string SHOW_PDF_FILTER {
            get {
                return ResourceManager.GetString("SHOW_PDF_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điện thoại: .
        /// </summary>
        internal static string SHOW_PHONE_NUMBER {
            get {
                return ResourceManager.GetString("SHOW_PHONE_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên sản phẩm.
        /// </summary>
        internal static string SHOW_PRODUCT_NAME {
            get {
                return ResourceManager.GetString("SHOW_PRODUCT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BÁO CÁO BÁN HÀNG.pdf.
        /// </summary>
        internal static string SHOW_RP_SALES_PDF_NAME {
            get {
                return ResourceManager.GetString("SHOW_RP_SALES_PDF_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BÁO CÁO BÁN HÀNG_.
        /// </summary>
        internal static string SHOW_RP_SALES_XLS_NAME {
            get {
                return ResourceManager.GetString("SHOW_RP_SALES_XLS_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biểu đồ doanh số.
        /// </summary>
        internal static string SHOW_SALES_CHART {
            get {
                return ResourceManager.GetString("SHOW_SALES_CHART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn 1 dòng để xóa.
        /// </summary>
        internal static string SHOW_SELECT_FOR_DEL {
            get {
                return ResourceManager.GetString("SHOW_SELECT_FOR_DEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn 1 dòng để sửa.
        /// </summary>
        internal static string SHOW_SELECT_FOR_EDIT {
            get {
                return ResourceManager.GetString("SHOW_SELECT_FOR_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cài đặt hiển thị sản phẩm.
        /// </summary>
        internal static string SHOW_SETTING_PR {
            get {
                return ResourceManager.GetString("SHOW_SETTING_PR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cài đặt hiển thị bàn.
        /// </summary>
        internal static string SHOW_SETTING_TB {
            get {
                return ResourceManager.GetString("SHOW_SETTING_TB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bàn/Khách hàng: .
        /// </summary>
        internal static string SHOW_TABLE_CUS {
            get {
                return ResourceManager.GetString("SHOW_TABLE_CUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bàn  trống.
        /// </summary>
        internal static string SHOW_TABLE_EMPTY {
            get {
                return ResourceManager.GetString("SHOW_TABLE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách bàn.
        /// </summary>
        internal static string SHOW_TABLE_LIST {
            get {
                return ResourceManager.GetString("SHOW_TABLE_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gộp bàn.
        /// </summary>
        internal static string SHOW_TABLE_MERGE {
            get {
                return ResourceManager.GetString("SHOW_TABLE_MERGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã số thuế: .
        /// </summary>
        internal static string SHOW_TAX_CODE {
            get {
                return ResourceManager.GetString("SHOW_TAX_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  sang .
        /// </summary>
        internal static string SHOW_TO {
            get {
                return ResourceManager.GetString("SHOW_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  đến ngày .
        /// </summary>
        internal static string SHOW_TO_DAY {
            get {
                return ResourceManager.GetString("SHOW_TO_DAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  đến năm .
        /// </summary>
        internal static string SHOW_TO_YEAR {
            get {
                return ResourceManager.GetString("SHOW_TO_YEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhấn chuột phải vào lưới để sửa hoặc xóa.
        /// </summary>
        internal static string SHOW_TOOLTIP_HELP {
            get {
                return ResourceManager.GetString("SHOW_TOOLTIP_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cài đặt kích thước sản phẩm.
        /// </summary>
        internal static string SHOW_TOOLTIP_SET_PR {
            get {
                return ResourceManager.GetString("SHOW_TOOLTIP_SET_PR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cài đặt kích thước bàn.
        /// </summary>
        internal static string SHOW_TOOLTIP_SET_TB {
            get {
                return ResourceManager.GetString("SHOW_TOOLTIP_SET_TB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng tiền:.
        /// </summary>
        internal static string SHOW_TOTAL_MN {
            get {
                return ResourceManager.GetString("SHOW_TOTAL_MN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng tiền.
        /// </summary>
        internal static string SHOW_TOTAL_MONEY {
            get {
                return ResourceManager.GetString("SHOW_TOTAL_MONEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn giá.
        /// </summary>
        internal static string SHOW_UNIT_PRICE {
            get {
                return ResourceManager.GetString("SHOW_UNIT_PRICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang xuất file pdf, vui lòng chờ....
        /// </summary>
        internal static string SHOW_WAIT_EXPORT {
            get {
                return ResourceManager.GetString("SHOW_WAIT_EXPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang xuất file, vui lòng chờ....
        /// </summary>
        internal static string SHOW_WAIT_EXPORT_FILE {
            get {
                return ResourceManager.GetString("SHOW_WAIT_EXPORT_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khách hàng.
        /// </summary>
        internal static string SHOW_XLS_CUS {
            get {
                return ResourceManager.GetString("SHOW_XLS_CUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày.
        /// </summary>
        internal static string SHOW_XLS_DATE {
            get {
                return ResourceManager.GetString("SHOW_XLS_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhân viên.
        /// </summary>
        internal static string SHOW_XLS_EM {
            get {
                return ResourceManager.GetString("SHOW_XLS_EM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel Documents (*.xls)|*.xls.
        /// </summary>
        internal static string SHOW_XLS_FILTER {
            get {
                return ResourceManager.GetString("SHOW_XLS_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã hóa đơn.
        /// </summary>
        internal static string SHOW_XLS_ID {
            get {
                return ResourceManager.GetString("SHOW_XLS_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thành tiền.
        /// </summary>
        internal static string SHOW_XLS_INTO_MN {
            get {
                return ResourceManager.GetString("SHOW_XLS_INTO_MN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mặt hàng.
        /// </summary>
        internal static string SHOW_XLS_PR {
            get {
                return ResourceManager.GetString("SHOW_XLS_PR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng.
        /// </summary>
        internal static string SHOW_XLS_QUANTILY {
            get {
                return ResourceManager.GetString("SHOW_XLS_QUANTILY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bàn.
        /// </summary>
        internal static string SHOW_XLS_TB {
            get {
                return ResourceManager.GetString("SHOW_XLS_TB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BÁO CÁO BÁN HÀNG.
        /// </summary>
        internal static string SHOW_XLS_TITLE_NAME {
            get {
                return ResourceManager.GetString("SHOW_XLS_TITLE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá tiền.
        /// </summary>
        internal static string SHOW_XLS_UN_PRC {
            get {
                return ResourceManager.GetString("SHOW_XLS_UN_PRC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Năm .
        /// </summary>
        internal static string SHOW_YEAR {
            get {
                return ResourceManager.GetString("SHOW_YEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap source {
            get {
                object obj = ResourceManager.GetObject("source", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap store16 {
            get {
                object obj = ResourceManager.GetObject("store16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sytem {
            get {
                object obj = ResourceManager.GetObject("sytem", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap table16 {
            get {
                object obj = ResourceManager.GetObject("table16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap unnamed {
            get {
                object obj = ResourceManager.GetObject("unnamed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap user_icon {
            get {
                object obj = ResourceManager.GetObject("user-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap user16 {
            get {
                object obj = ResourceManager.GetObject("user16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap users {
            get {
                object obj = ResourceManager.GetObject("users", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap view16 {
            get {
                object obj = ResourceManager.GetObject("view16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ViFlag {
            get {
                object obj = ResourceManager.GetObject("ViFlag", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
